"""customized the user model for the two kinds of users

Revision ID: 20805c3fda12
Revises: 
Create Date: 2024-06-01 18:28:04.654968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20805c3fda12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_teacher', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_learner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_learner')
        batch_op.drop_column('is_teacher')

    # ### end Alembic commands ###
